from __future__ import annotations

from tkinter import BOTH, END, LEFT, RIGHT, WORD, X, Y, Canvas, StringVar, Text
from tkinter import ttk

from frontends.tk.provider_models import ProviderRow
from frontends.tk.ui_config import COLORS


class DetailPanelWorkflowMixin:
    """封裝右側細節抽屜的 widget 建置與文字更新。

    這個 mixin 不決定安裝、移除、修復或爬蟲策略，只把 provider/dataset 選取後的
    可視狀態集中管理，降低主視窗類別同時持有 layout 與資料顯示細節的負擔。
    """

    def _build_detail_panel(self, parent: ttk.Frame) -> None:
        # Detail panel 是「商店頁」概念：顯示來源狀態、官方入口、AI 說明與可執行 action。
        self.detail_parent = parent
        self.detail = ttk.Frame(parent, style="Panel.TFrame", width=self.detail_width())
        self.detail.pack_propagate(False)
        self.detail_wrap_labels: list[ttk.Label] = []
        self.detail_star_var = StringVar(value="☆")
        self.detail_title_var = StringVar(value="選取一個資料源")
        self.detail_owner_var = StringVar(value="像 Steam 商店頁一樣查看用途、狀態與官方入口。")
        self.detail_category_var = StringVar(value="")
        self.detail_auth_var = StringVar(value="")
        self.detail_status_var = StringVar(value="")
        self.detail_scope_var = StringVar(value="")
        self.detail_urls_var = StringVar(value="")
        self.ai_summary_placeholder = self.tr("按「AI 產生說明」後，目前選取的 AI profile 產生的描述會顯示在這裡。", "Descriptions generated by the selected AI profile will appear here after you click AI description.")

        header = ttk.Frame(self.detail, style="Panel.TFrame")
        header.pack(fill=X, padx=18, pady=(18, 10))
        ttk.Button(header, text="×", width=3, command=self.close_detail_drawer).pack(side=RIGHT, padx=(10, 0))
        ttk.Button(header, textvariable=self.detail_star_var, width=3, command=self.toggle_active_star).pack(side=LEFT, padx=(0, 10))
        title_label = ttk.Label(header, textvariable=self.detail_title_var, style="DetailTitle.TLabel", wraplength=self.detail_content_wraplength())
        title_label.pack(side=LEFT, fill=X, expand=True)
        self.detail_wrap_labels.append(title_label)

        scroll_area = ttk.Frame(self.detail, style="Panel.TFrame")
        scroll_area.pack(fill=BOTH, expand=True)
        self.detail_canvas = Canvas(scroll_area, bg=COLORS["panel"], highlightthickness=0, borderwidth=0)
        self.detail_scrollbar = ttk.Scrollbar(scroll_area, orient="vertical", command=self.detail_canvas.yview)
        self.detail_canvas.configure(yscrollcommand=self.detail_scrollbar.set)
        self.detail_scrollbar.pack(side=RIGHT, fill=Y)
        self.detail_canvas.pack(side=LEFT, fill=BOTH, expand=True)
        self.detail_body = ttk.Frame(self.detail_canvas, style="Panel.TFrame")
        self.detail_canvas_window = self.detail_canvas.create_window((0, 0), window=self.detail_body, anchor="nw")
        self.detail_body.bind("<Configure>", self.update_detail_scrollregion)
        self.detail_canvas.bind("<Configure>", self.on_detail_canvas_configure)
        self.detail_canvas.bind("<MouseWheel>", self.on_detail_mousewheel)
        self.detail_body.bind("<MouseWheel>", self.on_detail_mousewheel)

        owner_label = ttk.Label(self.detail_body, textvariable=self.detail_owner_var, style="DetailMuted.TLabel", wraplength=self.detail_content_wraplength())
        owner_label.pack(anchor="w", fill=X, padx=18, pady=(0, 10))
        self.detail_wrap_labels.append(owner_label)

        self.preview_box = Text(
            self.detail_body,
            height=7,
            wrap=WORD,
            bg=COLORS["bg"],
            fg=COLORS["muted"],
            relief="flat",
            padx=14,
            pady=12,
            font=("Helvetica", 11),
        )
        self.preview_box.pack(fill=X, padx=18, pady=(18, 14))
        self.preview_box.insert("1.0", self.tr("OpenGraph / 官方頁面 metadata 擷取後，預覽會顯示在這裡。", "Preview metadata will appear here after OpenGraph/official-page extraction."))
        self.preview_box.configure(state="disabled")

        ttk.Label(self.detail_body, text=self.tr("AI 生成描述", "AI generated description"), style="DetailSection.TLabel").pack(anchor="w", padx=18, pady=(4, 2))
        self.ai_summary_box = Text(
            self.detail_body,
            height=7,
            wrap=WORD,
            bg=COLORS["bg"],
            fg=COLORS["muted"],
            relief="flat",
            padx=14,
            pady=12,
            font=("Helvetica", 11),
        )
        self.ai_summary_box.pack(fill=X, padx=18, pady=(0, 14))
        self.set_ai_summary_text(self.ai_summary_placeholder)

        for label, var in [
            (self.tr("標籤", "TAGS"), self.detail_category_var),
            (self.tr("存取方式", "ACCESS"), self.detail_auth_var),
            (self.tr("狀態", "STATUS"), self.detail_status_var),
            (self.tr("範圍", "SCOPE"), self.detail_scope_var),
            (self.tr("官方連結", "OFFICIAL LINKS"), self.detail_urls_var),
        ]:
            ttk.Label(self.detail_body, text=label, style="DetailSection.TLabel").pack(anchor="w", padx=18, pady=(10, 2))
            value_label = ttk.Label(self.detail_body, textvariable=var, style="DetailText.TLabel", wraplength=self.detail_content_wraplength())
            value_label.pack(anchor="w", fill=X, padx=18)
            self.detail_wrap_labels.append(value_label)

        actions = ttk.Frame(self.detail, style="Panel.TFrame")
        actions.pack(fill=X, padx=18, pady=(12, 18))
        action_specs = [
            ("開啟文件", self.open_active_docs),
            ("AI 產生說明", self.generate_active_summary),
            ("檢查 Metadata", self.check_active_metadata),
            ("驗證本地資產", self.verify_active_assets),
            ("加入下載計畫", self.select_active_provider),
            ("標記已納管", self.manage_active_provider),
            ("解除納管", self.unmanage_active_provider),
            ("移除本地資料", self.uninstall_active_provider),
            ("編輯描述", self.edit_active_provider),
        ]
        actions.columnconfigure(0, weight=1)
        actions.columnconfigure(1, weight=1)
        for index, (label, command) in enumerate(action_specs):
            ttk.Button(actions, text=label, style="Action.TButton", command=command).grid(
                row=index // 2,
                column=index % 2,
                sticky="ew",
                padx=(0, 6) if index % 2 == 0 else (6, 0),
                pady=(0, 8),
            )

    def update_detail_panel(self, row: ProviderRow | None) -> None:
        if row is None:
            self.detail_star_var.set("☆")
            self.detail_title_var.set("選取一個資料源")
            self.detail_owner_var.set("像 Steam 商店頁一樣查看用途、狀態與官方入口。")
            self.detail_category_var.set("")
            self.detail_auth_var.set("")
            self.detail_status_var.set("")
            self.detail_scope_var.set("")
            self.detail_urls_var.set("")
            self.set_preview_text(self.tr("OpenGraph / 官方頁面 metadata 擷取後，預覽會顯示在這裡。", "Preview metadata will appear here after OpenGraph/official-page extraction."))
            self.set_ai_summary_text(self.ai_summary_placeholder)
            return

        self.detail_star_var.set(row.star_label)
        self.detail_title_var.set(row.name)
        self.detail_owner_var.set(row.owner)
        self.detail_category_var.set(row.category_label)
        access = row.auth_type
        if row.key_env_var:
            access = f"{access}\n{self.tr('環境變數', 'Env')}: {row.key_env_var}"
        self.detail_auth_var.set(access)
        self.detail_status_var.set(
            f"{self.tr('遠端', 'Remote')}: {row.status_label} / {row.update_label}\n"
            f"{self.tr('本地', 'Local')}: {row.local_label}\n"
            f"{self.tr('已發現資料集', 'Discovered datasets')}: {len(self.datasets_by_provider.get(row.provider_id, []))}\n"
            f"{self.tr('安裝 ID', 'Install ID')}: {row.install_id or self.tr('未納管', 'not managed')}\n"
            f"{self.tr('下載', 'Download')}: "
            f"{self.localized_download_label(row.download_eligibility)} - "
            f"{self.localized_download_reason(row.download_eligibility)}"
        )
        self.detail_scope_var.set(row.geographic_scope)
        links = [
            f"{self.tr('文件', 'Docs')}: {row.docs_url}" if row.docs_url else "",
            f"API: {row.api_base_url}" if row.api_base_url else "",
            f"{self.tr('註冊', 'Signup')}: {row.signup_url}" if row.signup_url else "",
        ]
        self.detail_urls_var.set("\n".join(link for link in links if link))
        self.set_preview_text(self.provider_description(row))
        self.set_ai_summary_text(row.notes or self.tr("尚未產生 AI 描述。", "No AI description generated yet."))

    def provider_description(self, row: ProviderRow) -> str:
        if row.notes:
            return row.notes
        category_hint = row.category_label or "data"
        if self.ui_language != "en-US":
            return (
                f"{row.name} 是由 {row.owner} 提供的官方 {category_hint} 資料來源。"
                "之後擷取官方 metadata 後，這裡會顯示更完整的描述與預覽。"
            )
        return (
            f"{row.name} is an official {category_hint} source from {row.owner}. "
            "A richer description and visual preview will be populated from official metadata pages."
        )

    def set_preview_text(self, text: str) -> None:
        self.preview_box.configure(state="normal")
        self.preview_box.delete("1.0", END)
        self.preview_box.insert("1.0", text)
        self.preview_box.configure(state="disabled")

    def set_ai_summary_text(self, text: str) -> None:
        self.ai_summary_box.configure(state="normal")
        self.ai_summary_box.delete("1.0", END)
        self.ai_summary_box.insert("1.0", text)
        self.ai_summary_box.configure(state="disabled")
