param(
    [string] $Python = "py",
    [switch] $Force
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Resolve-Path (Join-Path $ScriptDir "..")
Set-Location $ProjectRoot

$hookPath = (git rev-parse --git-path hooks/pre-push).Trim()
if (-not $hookPath) {
    throw "Cannot resolve .git/hooks/pre-push path."
}
$hookFullPath = if ([System.IO.Path]::IsPathRooted($hookPath)) {
    $hookPath
} else {
    Join-Path $ProjectRoot $hookPath
}
$hookParent = Split-Path -Parent $hookFullPath
New-Item -ItemType Directory -Force $hookParent | Out-Null

if ((Test-Path $hookFullPath) -and -not $Force) {
    $existing = Get-Content -Path $hookFullPath -Raw -ErrorAction SilentlyContinue
    if ($existing -notmatch "APIkeys_collection pre-push smoke hook") {
        throw "pre-push hook already exists and is not managed by APIkeys_collection. Re-run with -Force only after reviewing it."
    }
}

$hook = @"
#!/bin/sh
# APIkeys_collection pre-push smoke hook
# Generated by scripts/install_pre_push_hook.ps1. Re-run that script after changing the preferred Python command.

set -e

repo_root=`$(git rev-parse --show-toplevel)
cd "`$repo_root"

if command -v cmd.exe >/dev/null 2>&1; then
    cmd.exe /c scripts\\pre_push_smoke.cmd -Python "$Python"
elif command -v pwsh >/dev/null 2>&1; then
    pwsh -NoProfile -ExecutionPolicy Bypass -File scripts/pre_push_smoke.ps1 -Python "$Python"
elif command -v powershell.exe >/dev/null 2>&1; then
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File scripts/pre_push_smoke.ps1 -Python "$Python"
else
    echo "No PowerShell runtime found for APIkeys_collection pre-push smoke." >&2
    exit 1
fi
"@

# Git hook 由 sh 讀取；使用無 BOM UTF-8 避免 shebang 前出現隱藏位元組。
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($hookFullPath, $hook, $utf8NoBom)
$chmod = Get-Command chmod -ErrorAction SilentlyContinue
if ($chmod) {
    # macOS/Linux 的 Git hook 需要 executable bit；Windows 上沒有 chmod 時可安全略過。
    & $chmod +x $hookFullPath | Out-Null
}

Write-Host "[install-pre-push-hook] wrote $hookFullPath"
Write-Host "[install-pre-push-hook] hook command: scripts\\pre_push_smoke.cmd -Python $Python"
Write-Host "[install-pre-push-hook] bypass for emergency pushes: git push --no-verify"
